[package]
name = "client"
version = "0.1.0"
authors = ["David LeGare <excaliburhissheath@gmail.com>"]

[dependencies]
core = { path = "../core" }
futures = "0.1"
gl-winit = { git = "https://github.com/randomPoison/polygon" }
polygon = { git = "https://github.com/randomPoison/polygon" }
sumi = { path = "../sumi" }
tokio-core = "0.1"
winit = "0.7"
