[package]
name = "client"
version = "0.1.0"
authors = ["David LeGare <excaliburhissheath@gmail.com>"]

[dependencies]
bytes = "0.4"
core = { path = "../core" }
futures = "0.1"
gl-winit = { git = "https://github.com/randomPoison/polygon" }
polygon = { git = "https://github.com/randomPoison/polygon" }
tokio-io = "0.1"
tokio-core = "0.1"
tokio-proto = "0.1"
tokio-service = "0.1"
winit = "0.7"
