[package]
name = "core"
version = "0.1.0"
authors = ["David LeGare <excaliburhissheath@gmail.com>"]

[dependencies]
cgmath = { version = "0.15", features = ["mint", "serde"] }
futures = "0.1"
rand = "0.3"
serde = { version = "1.0", features = ["derive"] }
